package br.senac.taskmaster.telas;

import br.senac.taskmaster.telas.TarefaDAO;
import br.senac.taskmaster.telas.TarefaDTO;
import br.senac.taskmaster.telas.UsuarioDTO;
import javax.swing.*;
import java.awt.event.*;

public class TelaNovaTarefaVIEW extends JFrame {

    private TelaDashboardVIEW dashboard;
    private UsuarioDTO usuarioLogado;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JComboBox<String> campoStatus;
    private TelaDashboardVIEW dashboardView;

    // Componentes da interface
    private JTextField campoDescricao;
    private JTextField campoPrazo;
    private JComboBox<String> comboStatus;

    public TelaNovaTarefaVIEW(UsuarioDTO usuarioLogado, TelaDashboardVIEW dashboard) {
        this.usuarioLogado = usuarioLogado;
        this.dashboard = dashboard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtResponsavel = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblPrazo = new javax.swing.JLabel();
        txtPrazo1 = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        lblTitulo1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(33, 37, 41));
        lblTitulo.setText("Responsável ");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(30, 40, 100, 25);

        lblDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(33, 37, 41));
        lblDescricao.setText("Descrição:");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(30, 70, 100, 25);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(33, 37, 41));
        lblStatus.setText("Status:");
        getContentPane().add(lblStatus);
        lblStatus.setBounds(30, 150, 90, 25);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(248, 249, 250));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(210, 220, 130, 30);

        txtResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResponsavel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        getContentPane().add(txtResponsavel);
        txtResponsavel.setBounds(140, 40, 200, 22);

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(140, 70, 200, 25);

        btnSalvar.setBackground(new java.awt.Color(0, 123, 255));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(248, 249, 250));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(60, 230, 130, 30);

        lblPrazo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrazo.setForeground(new java.awt.Color(33, 37, 41));
        lblPrazo.setText("Prazo (dd/MM/yyyy):");
        getContentPane().add(lblPrazo);
        lblPrazo.setBounds(30, 110, 150, 25);

        txtPrazo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrazo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        getContentPane().add(txtPrazo1);
        txtPrazo1.setBounds(190, 110, 150, 25);

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Em andamento", "Concluída" }));
        cmbStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        getContentPane().add(cmbStatus);
        cmbStatus.setBounds(120, 150, 230, 25);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(33, 37, 41));
        lblTitulo1.setText("Título:");
        getContentPane().add(lblTitulo1);
        lblTitulo1.setBounds(30, 10, 100, 25);

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        getContentPane().add(txtTitulo);
        txtTitulo.setBounds(140, 10, 200, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String titulo = txtTitulo.getText().trim(); // <-- Certifique-se de que txtTitulo existe
        String descricao = txtDescricao.getText().trim();
        String status = cmbStatus.getSelectedItem().toString();
        String responsavel = txtResponsavel.getText().trim();
        String prazo = txtPrazo1.getText().trim();

// Verifica se algum campo está vazio
        if (titulo.isEmpty() || descricao.isEmpty() || status.isEmpty() || responsavel.isEmpty() || prazo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Verifica se o prazo está no formato correto (dd/MM/yyyy)
        if (!prazo.matches("\\d{2}/\\d{2}/\\d{4}")) {
            JOptionPane.showMessageDialog(this, "O prazo deve estar no formato dd/MM/yyyy!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Criar DTO
        TarefaDTO tarefaDTO = new TarefaDTO();
        tarefaDTO.setTitulo(titulo); // <-- Adicionado
        tarefaDTO.setDescricao(descricao);
        tarefaDTO.setStatus(status);
        tarefaDTO.setResponsavel(responsavel);
        tarefaDTO.setPrazo(prazo);
        tarefaDTO.setUsuarioId(usuarioLogado.getId());

// Salvar no banco
        TarefaDAO tarefaDAO = new TarefaDAO();
        boolean sucesso = tarefaDAO.adicionarTarefa(tarefaDTO, usuarioLogado.getId());

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Tarefa salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            if (dashboardView != null) {
                dashboardView.atualizarTabelaTarefas();
                dashboardView.setVisible(true);
            }

            this.dispose(); // Fecha a tela de nova tarefa

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar a tarefa.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (dashboard != null) {
            dashboard.setVisible(true);
        } else {
            new TelaDashboardVIEW(usuarioLogado).setVisible(true);
        }
        this.dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPrazo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPrazo1;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
